services:
  house:
    image: ghcr.io/jackharrhy/get-house-pls:main
    build:
      context: .
      dockerfile: Dockerfile
    # Chrome needs more than Docker's default 64MB /dev/shm
    shm_size: "2gb"
    volumes:
      - ./data:/data
    environment:
      - HOUSE_DATABASE=/data/house.db
    env_file:
      - .env
